apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-db
  template:
    metadata:
      labels:
        app: task-db
    spec:
      containers:
        - name: task-db
          image: mysql:8
          ports:
            - containerPort: 3307
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-db-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: taskdb
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: task-db-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-db-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: task-db-pv
              mountPath: /var/lib/mysql
            - name: sql-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: task-db-pv
          persistentVolumeClaim:
            claimName: task-db-pvc
        - name: sql-scripts
          configMap:
            name: task-db-sql
