# apiVersion: v1
# kind: Secret
# metadata:
#   name: auth-secret
# type: Opaque
# stringData:
#   JWT_SECRET: jwt-secret-not-here
#   DB_HOST: db-not-here
#   DB_USER: db-user-not-here
#   DB_PASSWORD: db-password-user-not-here
#   DB_NAME: db-name-not-here

apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
type: Opaque
stringData:
  JWT_SECRET: this_is_a_secret
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_USER: authuser
  MYSQL_PASSWORD: authpass